version: '3'

services:
  worker:
    build: .
    env_file: .env
    networks:
      - barad-dur_barad-dur
    volumes:
      - ./vk_service:/app/vk_service/
    command: python -m vk_service


networks:
  barad-dur_barad-dur:
    external: true